import { beforeEach, expect, it, vi } from 'vitest'
vi.mock('./env', () => ({ isTauri: false, isDesktopTauri: false, isMobile: false }))
beforeEach(() => { vi.resetModules(); localStorage.clear() })
it('copies survive restart and removal of the original catalog entry', async () => {
  let cat = await import('./catalog')
  cat.catalogAdd(['e:/a.jpg'])
  cat.catalogAddCopy({id:'copy:a',path:'e:/a.jpg',name:'a · 副本 1.jpg'})
  cat.catalogSetActive('e:/a.jpg','copy:a')
  cat.catalogRemove('e:/a.jpg')
  await cat.flushPersist()
  vi.resetModules(); cat = await import('./catalog')
  expect(cat.loadCatalog().paths).toEqual([])
  expect(cat.loadCatalog().copies).toHaveLength(1)
  expect(cat.loadCatalog().activeId).toBe('copy:a')
  cat.catalogRemoveCopy('copy:a'); await cat.flushPersist()
  vi.resetModules(); cat = await import('./catalog')
  expect(cat.loadCatalog().copies).toEqual([])
})
it('does not report success when catalog storage fails', async () => {
  const cat = await import('./catalog')
  cat.catalogAddCopy({id:'copy:a',path:'e:/a.jpg',name:'copy.jpg'})
  const spy = vi.spyOn(Storage.prototype,'setItem').mockImplementation(() => { throw new Error('disk full') })
  await expect(cat.flushPersist()).rejects.toThrow('disk full')
  spy.mockRestore()
  await cat.flushPersist()
  expect(JSON.parse(localStorage.getItem('framelab-catalog')!).copies).toHaveLength(1)
})
